### ISSUE TITLE
CSS formatting tags

### ISSUE THREAD

**Issue by mc12345678** [mesnitu/EasyPopulate-4.0-BookX#12]
Based on the request, it would appear that the styling that currently remains in EP4 should be modified to be controlled by stylesheets (CSS).  By doing so, bookX could load a stylesheet to override default EP4 styling as desired.  This change is fully accepted and will be next up in the modifications to EP4.

**Comment by mesnitu** [comment]
In the way, I would also suggest removing all those table border=1, cellspacing and cellpadding. This is very old. The ID on that table, or some class in the th headers, would be  nice to give style freedom.

**Comment by mc12345678** [comment]
Technically because of the way ZC is headed in the admin, the "table" structure is more than likely going to have to go away.... Curious about how it will look on a mobile as I'm actually satisifed with a "full" screen view on mobile, but in the end it may not look quite right/work left as a table.

**Comment by mesnitu** [comment]
All css ,js now blends ok, so this can be close
